---
title: East Civil War Letters
email: benwbrum@gmail.com
owner: Ben W. Brumfield
description: "<p>The East documents were found in an abandoned building near Cherrystone
  Creek in the early 1970s, and include one empty envelope addressed to John C. East
  and one letter (with envelope) from George W. East to Thomas C. East.</p>\n\n<p>George
  W. East enlisted in the 53rd VA Infantry, Company I, when he was seventeen years
  old.  He travelled from Chatham to Suffolk to join his unit, then fell sick and
  was hospitalized at Suffolk in March 1862. Apparently he was recovered enough to
  join his regiment and write this letter home on August 6, 1862.  He was hospitalized
  with \"typhoid pneumonia\" at Chimborazo Hospital in Richmond Feb 16, 1863, then
  transferred to a hospital in Danville April 18, 1863 where he was released on sick
  furlough to his home.</p>  \n\n<p>He returned to duty on the 28 May, participated
  in Pickett's Charge and was captured at Gettysburg July 3, 1863.  He was imprisoned
  at Ft. Delaware, Del. July \"5/12\"\n1863, then was transferred to Point Lookout,
  MD Oct 26, 1863.  There he died of typhoid pneumonia on Feb 6, 1864.</p>\n\n<p>Thomas
  C. East filed a claim for $215 with the Confederate War Dept.\non deceased George
  W. East on Jan 10, 1865.  This was approved, then\nrejected by the paymaster in
  Chatham on the grounds that Thomas had provided no evidence of his son's death.
  Thomas re-filed, including a letter from George's fellow-POW Shemi Watson mentioning
  the death of George East.  The claim was paid March 1865.</p>"
theme: minimal-mistakes-jekyll
plugins:
- jekyll-feed
defaults:
- scope:
    path: ''
  values:
    layout: archive
